
export const variants = [
  { id: 'repeat-a', edit: 'none', amount: 0 }, { id: 'repeat-b', edit: 'none', amount: 0 },
  { id: 'content-a', edit: 'content', amount: 1 }, { id: 'content-b', edit: 'content', amount: 2 },
  { id: 'intent-a', edit: 'move', amount: 70, intentional: true }, { id: 'intent-b', edit: 'move', amount: 125, intentional: true },
  { id: 'clip-a', edit: 'clip', amount: 150 }, { id: 'clip-b', edit: 'clip', amount: 100 }, { id: 'clip-c', edit: 'clip', amount: 60 },
  { id: 'cover-a', edit: 'cover', amount: 100 }, { id: 'cover-b', edit: 'cover', amount: 160 }, { id: 'cover-c', edit: 'cover', amount: 210 },
  { id: 'outside-a', edit: 'outside', amount: 0 }, { id: 'outside-b', edit: 'outside', amount: 40 },
  { id: 'absent-a', edit: 'absent', amount: 0 }, { id: 'absent-b', edit: 'absent', amount: 0 },
  { id: 'shift-a', edit: 'move', amount: 95 }, { id: 'shift-b', edit: 'move', amount: 155 },
] as const;
export const families = ['nested-file-inspector', 'expanded-questions', 'appointment-swimlane'] as const;
export type Family = typeof families[number];
export type Variant = typeof variants[number];
const escape = (text: string) => text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
export function documentFor(family: Family, variant: Variant, after: boolean): string {
  const active = after ? variant.edit : 'none', amount = variant.amount;
  const placement = { 'nested-file-inspector': { left: 26, top: 130, outside: 470 }, 'expanded-questions': { left: 32, top: 105, outside: 675 }, 'appointment-swimlane': { left: 205, top: 32, outside: 635 } }[family];
  const left = active === 'outside' ? placement.outside + amount : placement.left + (active === 'move' ? amount : 0);
  const hidden = active === 'absent';
  const target = `<div id="target" style="left:${left}px;top:${placement.top}px;visibility:${hidden ? 'hidden' : 'visible'}"><span id="target-label" style="width:${active === 'clip' ? amount : 240}px">${family === 'nested-file-inspector' ? 'Restore previous revision' : family === 'expanded-questions' ? 'Read the complete answer' : 'Consultation · Garden room'}</span></div>`;
  const cover = active === 'cover' ? `<aside id="occluder" style="left:${left + 12}px;top:${placement.top + 12}px;width:${amount}px">Additional details</aside>` : '';
  let content: string, css: string;
  const contentValue = active === 'content' ? ['Update saved at 10:42', 'Update saved at 11:08'][amount - 1] : 'Update saved at 09:15';
  if (family === 'nested-file-inspector') {
    css = `.shell{display:grid;grid-template-columns:270px 570px;gap:22px}.tree{background:#edf1f7;padding:20px;border:1px solid #95a7bf;height:720px}.tree ul{padding-left:24px;list-style:none;line-height:2.1}.tree li::before{content:'▸ ';color:#456}.inspector{height:920px;background:white;padding:20px;border:1px solid #b5bfcc}#container{position:relative;width:550px;height:310px;border:3px solid #4b6686;background:#f6f9fe;margin-left:-10px}.properties{display:grid;grid-template-columns:120px 1fr;gap:14px;margin-top:35px}.preview{height:340px;margin-top:45px;border:1px dashed #93a8bb;background:repeating-linear-gradient(#fff,#fff 25px,#e8edf3 26px)}`;
    content = `<h1>Archive inspector</h1><p class="meta">${escape(contentValue)}</p><div class="shell"><nav class="tree"><h2>Archive</h2><ul><li>Projects<ul><li>Spring notes<ul><li>Overview.md</li><li>References</li><li>Drafts<ul><li>Revision 03</li><li>Revision 04</li></ul></li></ul></li><li>Autumn notes</li></ul></li><li>Shared files</li></ul></nav><article class="inspector"><h2>Revision controls</h2><div id="container"><p>Selected revision: 04</p>${target}${cover}</div><dl class="properties"><dt>Format</dt><dd>Markdown</dd><dt>Owner</dt><dd>Documentation team</dd><dt>History</dt><dd>Four saved revisions</dd></dl><div class="preview">Document preview</div></article></div>`;
  } else if (family === 'expanded-questions') {
    css = `.questions{width:830px}details{border:1px solid #b8b1cc;background:white;margin:18px 0;padding:18px}summary{font-size:22px;font-weight:bold;color:#453465}.answer{padding:18px 26px;line-height:1.7}#container{position:relative;width:790px;height:260px;border:3px solid #655380;background:#f6f1fb}.intro{height:460px;background:linear-gradient(#ebe4f3,#f6f7fa);padding:34px;border-radius:8px}.footer{height:220px;padding:35px;border-top:2px solid #b8b1cc}`;
    content = `<h1>Community questions</h1><p class="meta">${escape(contentValue)}</p><div class="questions"><section class="intro"><h2>Using the community collection</h2><p>Answers are grouped by topic.</p><p>Choose a question to inspect its supporting explanation.</p></section><details open><summary>How are changes recorded?</summary><div class="answer">Every published revision has a dated note and a link to supporting details.</div></details><details open><summary>Where can I read the full explanation?</summary><div id="container"><p>The supporting guide contains the complete explanation.</p>${target}${cover}</div></details><details open><summary>Can I keep an offline copy?</summary><div class="answer">Yes. Save the complete document for later reading.</div></details><footer class="footer">Community documentation · All questions remain available.</footer></div>`;
  } else {
    css = `.schedule{width:1000px;background:#fff;border:1px solid #abc0b4;padding:22px}.hours{margin-left:170px;display:grid;grid-template-columns:repeat(5,150px);padding:20px 0;color:#315b48}.lane{display:flex;align-items:center;margin:14px 0;min-height:112px}.lane-name{width:165px;font-weight:bold}.ribbon{width:790px;height:120px;position:relative;border:3px solid #537e68;background:repeating-linear-gradient(90deg,#f2f8f4,#f2f8f4 147px,#c3d7cb 148px,#c3d7cb 150px)}.booking{position:absolute;background:#d3e4d6;border-left:5px solid #437851;padding:18px;width:190px;top:30px}.legend{display:flex;gap:40px;padding:30px;border-top:1px solid #abc0b4}.notes{height:450px;margin-top:20px;background:#f6faf7;padding:22px}#target{background:#266756!important}`;
    content = `<h1>Appointment ribbon</h1><p class="meta">${escape(contentValue)}</p><section class="schedule"><div class="hours"><span>09:00</span><span>10:00</span><span>11:00</span><span>12:00</span><span>13:00</span></div><div class="lane"><span class="lane-name">Cedar room</span><div class="ribbon"><div class="booking" style="left:25px">Morning check-in</div></div></div><div class="lane"><span class="lane-name">Garden room</span><div class="ribbon" id="container">${target}${cover}</div></div><div class="lane"><span class="lane-name">Library room</span><div class="ribbon"><div class="booking" style="left:455px">Planning session</div></div></div><div class="legend"><span>Confirmed appointment</span><span>Room availability</span></div><section class="notes"><h2>Visit notes</h2><p>Arrive ten minutes before the listed appointment.</p><p>Every room has step-free access.</p></section></section>`;
  }
  return `<!doctype html><html lang="en"><meta charset="utf-8"><title>Final holdout scene</title><style>html,body{margin:0;background:#f6f7fa;color:#233044;font:18px Arial,sans-serif}body{padding:28px}*{box-sizing:border-box}h1{font-size:34px;margin:0 0 12px}h2{font-size:23px}p{line-height:1.6}.meta{color:#536275;margin-bottom:28px}#container>p{padding:8px 24px}#target{position:absolute;width:270px;height:70px;background:#2d5983;border:2px solid #1f4265;color:white;padding:18px 12px;font-size:20px}#target-label{display:block;overflow:hidden;white-space:nowrap;line-height:30px;height:30px}#occluder{position:absolute;height:48px;background:#dca954;color:#392803;padding:12px 8px;font-size:14px;z-index:3;overflow:hidden;white-space:nowrap}${css}</style><main data-ready>${content}</main></html>`;
}
