import json
from pathlib import Path
import numpy as np

def read(name):return json.loads(Path(name).read_text())
def main():
    exp=read('artifacts/experiments.json');result=read('artifacts/model-results.json');ext=read('artifacts/extended-evaluation.json');stress=read('artifacts/stress-results.json');replay=read('artifacts/replay-results.json');gen=read('artifacts/generation.json');cal=read('web/public/models/calibration.json');manifest=read('web/public/models/manifest.json')
    lines=['# Experiment results','','Saved results for the released local + context model. The final structural holdout missed every clipping-positive page and produced many boundary-crossing false positives; occlusion and displacement transferred better. Original records remain in [artifacts](../artifacts).','','The original 24-family evaluation was rerun after correcting full-page screenshots, with unchanged splits and training recipe. Those families had already been observed. [Viewport-only results](../artifacts/viewport-only-audit/) and the earlier challenge belong to the superseded model. The separate final holdout below was evaluated after freezing the corrected model.','','## Dataset and training','',f"The corpus has {gen['pairs']:,} Chromium PNG pairs in 24 source families: {gen['bySplit']['train']} training, {gen['bySplit']['dev']} development, {gen['bySplit']['calibration']} calibration, and {gen['bySplit']['test']} test. The application generates candidates; rendered observations supply labels, with unknown supervision masked. See [Data and supervision](data.md).",'',f"The release model uses seed {result['selectedSeed']}, selected by development macro PR-AUC {result['selectionDevMacroPrAuc']:.4f}. Training source: `{manifest['trainingSourceSha']}`. Training uses two head-warmup epochs and four encoder-tuning epochs, with AdamW reset each epoch and frozen BatchNorm statistics. Comparisons use seeds 17, 29 and 43 with the same splits and labels; see [training configuration](../artifacts/training-config.json).",'','## Candidate classification','','| Method | Held-family macro PR-AUC | Repeats |','|---|---:|---:|']
    for name,label in [('uninformed_prior','Uninformed training prior'),('pixel_difference','Pixel difference density'),('difference_statistics','Difference statistics + logistic classifier')]:lines.append(f"| {label} | {exp['baselines'][name]['test']['macroPrAuc']:.4f} | Deterministic |")
    for kind,label in [('frozen','Frozen generic visual features'),('local_only','Fine-tuned local crops'),('local_context','Fine-tuned local + context')]:
        values=np.array([r['test']['macroPrAuc'] for r in exp['models'] if r['kind']==kind]);lines.append(f'| {label} | {values.mean():.4f} ± {values.std(ddof=1):.4f} SD | 3 seeds |')
    lines+=['','![Comparison from saved metrics](figures/comparison.png)','','Local-only has a slightly higher mean than local + context, within the variation across seeds. The release retains local + context. [Per-seed metrics and losses](../artifacts/experiments.json) retain every run.','','| Observation | Known candidates | Positive | Precision | Recall | F1 | PR-AUC |','|---|---:|---:|---:|---:|---:|---:|']
    for c in result['calibratedTest']['classes']:lines.append(f"| {c['label']} | {c['n']} | {c['positive']} | {c['precision']:.3f} | {c['recall']:.3f} | {c['f1']:.3f} | {c['prAuc']:.3f} |")
    b=ext['familyBootstrap'];lines += ['',f"The selected model's macro PR-AUC is {result['calibratedTest']['macroPrAuc']:.4f}; its 500-resample source-family percentile interval is [{b['macroPrAuc95Percentile'][0]:.4f}, {b['macroPrAuc95Percentile'][1]:.4f}]. This interval uses only three authored test families.",'','![Saved development curves](figures/training-curves.png)','','## Candidate coverage and complete-system recall','']
    c=ext['localization']['test'];lines += [f"There are {c['positiveObservationRegions']} positive observation regions across {c['pagePairs']} held-family pairs. Candidate recall is {c['recallAtPoint1Coverage']:.3f} at 10% ground-truth coverage and {c['recallAtPoint5Coverage']:.3f} at 50% coverage: respectively {c['missingAtPoint1']} and {c['missingAtPoint5']} regions are missed. Mean maximum coverage is {c['meanMaxCoverage']:.3f}, while mean maximum tightness is {c['meanMaxTightness']:.3f}. The average candidate count is {c['meanCandidatesPerPage']:.3f} per pair, p95 {c['p95CandidatesPerPage']:.1f}, maximum {c['maximumCandidatesPerPage']}; {c['zeroCandidatePages']} pairs have no candidate.",'','Ground-truth boxes join before/after element extents. The 10% association is permissive; coverage and tightness are reported separately.','', '| Observation | All positive regions | Captured | Missed | Complete-system recall |','|---|---:|---:|---:|---:|']
    for r in ext['endToEndObservationRecall']:lines.append(f"| {r['label']} | {r['allPositiveObservationRegions']} | {r['captured']} | {r['missed']} | {r['recall']:.3f} |")
    lines += ['','## Review budgets','','Pages rank by maximum candidate observation score. Budgets include candidate-free pages and measure capture of observation-bearing pages.','','| Method | Top 10% capture | Top 25% capture | Top 50% capture |','|---|---:|---:|---:|']
    for method,curve in ext['pageReviewBudgets'].items():lines.append('| '+method+' | '+' | '.join(f"{c['capturedObservationPages']}/{c['positiveObservationPages']} ({c['captureRate']:.3f})" for c in curve)+' |')
    lines += ['','DOM contracts use separate challenge and integration fixtures; they are not included in the visual classification metrics.','','## Calibration','','Calibration uses three separate families. A class needs at least 15 known positives and 15 known negatives; other outputs stay uncalibrated. The calibration target is observation frequency on these synthetic candidates.','','| Observation | Calibration n | Positive / negative | Status | Held-family Brier | Held-family ECE |','|---|---:|---:|---|---:|---:|']
    for c,r in zip(cal['classes'],result['testReliability']):lines.append(f"| {c['label']} | {c['n']} | {c['positive']} / {c['negative']} | {c['status']} | {r['brier']:.4f} | {r['ece']:.4f} |")
    lines += ['','![Reliability bins with real sample counts](figures/reliability.png)','','Calibration metrics cover generated candidates. [Full bin counts](../artifacts/model-results.json) remain available; missed candidates are outside these measurements.','','## Domain and type exclusions','','Secondary probes use seed 107. Training/epoch selection uses light English variants 0 and 2; dark English uses held-family variants 1 and 3. Japanese and Chinese text is separately authored on held structures. Chinese changes both script and theme.','','| Probe domain | Macro PR-AUC | Macro F1 |','|---|---:|---:|']
    for name,metric in stress['domainExclusion']['metrics'].items():lines.append(f"| {name} | {metric['macroPrAuc']:.4f} | {metric['macroF1']:.4f} |")
    symptom=stress['symptomExclusion'];c=symptom['metric']['classes'][1];lines += ['',f"The symptom-exclusion configuration removes {symptom['removedPages']} overlap-positive training page pairs before training. The excluded class has PR-AUC {c['prAuc']:.4f}, recall {c['recall']:.3f}, and F1 {c['f1']:.3f}. Its score is uncalibrated and the excluded class has no positive task supervision.",'','## Offline label replay','',f"The replay pool contains {replay['poolPages']} candidate-bearing training page pairs. Each strategy begins with the same 12 labeled pages per seed and uses budgets 12, 24, 48, and 96. Selecting a page reveals its existing labels. All strategies use the same frozen encoder, projection, logistic heads, seeds and update schedule. Candidate-free pages are excluded from this labeling pool.",'',f"Calibration-label cost is {replay['calibrationLabelCost']}; selection uses uncalibrated scores. The separate development-label cost is {replay['developmentLabelCost']} candidate-bearing page pairs. Development labels are outside the pool budget; human time was not measured.",'','| Strategy | 12 pages | 24 pages | 48 pages | 96 pages |','|---|---:|---:|---:|---:|']
    for strategy in ['random','uncertainty','uncertainty_diversity']:
        values=np.array([[c['test']['macroPrAuc'] for c in r['curve']] for r in replay['runs'] if r['strategy']==strategy]);lines.append('| '+strategy+' | '+' | '.join(f'{v:.4f}' for v in values.mean(0))+' |')
    lines += ['','![Offline replay results](figures/replay.png)','','Active selection did not consistently beat random selection. Records retain selected page IDs and candidate counts at each step.','','## Runtime and numerical parity','']
    t=ext['timing'];n=ext['numericalParity'];nd=read('artifacts/numerical-batch-diagnostic.json');wg=nd['exportGraph'];lines += [f"Measured on {t['platform']} with MPS training and CPU ONNX inference: full scene generation took {gen['seconds']:.2f} s and all nine primary neural comparisons plus associated evaluation took {result['seconds']:.2f} s. The ONNX file is {t['modelBytes']:,} bytes. Its measured cold load was {t['modelLoadMilliseconds']:.2f} ms, first inference {t['coldInferenceMilliseconds']:.2f} ms, warm median {t['warmInferenceMedianMilliseconds']:.2f} ms and p95 {t['warmInferenceP95Milliseconds']:.2f} ms over {t['warmTrials']} trials at batch 1. Each input has four 96 × 96 RGB crops plus 12 geometry values.",'',f"On {n['pairs']} real candidate inputs, maximum deployment-fused PyTorch/ONNX logit error was {n['maxLogitError']:.2g}, score error {n['maxScoreError']:.2g}, with {n['thresholdDisagreements']} threshold disagreements and ranking agreement {n['candidateRankingAgrees']}. The tolerance remains 1e-4. The raw, unfused float32 PyTorch comparison separately exceeded that initial logit budget (about 1.23e-4); its calibrated score difference stayed below 7.1e-6 with zero threshold differences. The raw comparison remains in [numerical diagnostics](../artifacts/numerical-batch-diagnostic.json). The ONNX graph contains no BatchNorm nodes, and standard PyTorch Conv/BN fusion independently agrees with its exported convolution weights within float32 rounding: maximum absolute difference {wg['maxFusedWeightDifference']:.3g}, maximum relative difference {wg['maxFusedWeightRelativeDifference']:.3g}, and maximum distance {wg['maxFusedWeightUlpDistance']} float32 ULPs. Browser parity tests cover decoded pixels, candidates, tensors, graph output and ranking.",'','[Preprocessing timings](../artifacts/preprocessing-timing.json) cover PNG decode, candidates and tensors; [end-to-end timings](../artifacts/end-to-end-timing.json) include process startup, disk transfer and CPU inference. URL capture and UI rendering are separate.','','## Reproduction','','```sh','node ml/generate.mjs','python -m ml.prepare','python -m ml.train --device mps --epochs 6','python -m ml.replay --device mps','node --import tsx ml/stress-generate.mjs','python -m ml.stress --device mps','python -m ml.numerical','python -m ml.evaluate','node --import tsx ml/benchmark.mjs','python -m ml.benchmark','python -m ml.feedback --build-buffer','python -m ml.figures','python -m ml.report','```','','Install browser dependencies first and use `--device cpu` where MPS is unavailable. These commands regenerate data and training results; routine tests do not require them.']
    holdout_path=Path('artifacts/final-holdout-results.json')
    holdout=read(str(holdout_path)) if holdout_path.exists() else {'modelSha256':None,'renderedPairs':0,'uniqueImagePairs':0,'familyCount':0,'publishedThresholds':{}}
    section=['','## Final structural holdout','',f"The corrected model was evaluated on {holdout['renderedPairs']} newly authored pairs ({holdout['uniqueImagePairs']} unique image pairs) from {holdout['familyCount']} structurally independent fixture sources. The release thresholds were frozen before predictions. These results did not change the model, thresholds or labels.",'', '| Observation | Known pages | Positive pages | F1 | Average precision | Missed positives |','|---|---:|---:|---:|---:|---:|']
    for name,c in holdout['publishedThresholds'].items():section.append(f"| {name} | {c['knownPages']} | {c['positivePages']} | {c['f1']:.3f} | {c['averagePrecision']:.3f} | {c['fn']} |")
    section += ['', 'Clipping missed every positive page; boundary crossing produced many false positives. [Raw holdout results](../artifacts/final-holdout-results.json) include per-family scores and both threshold policies.','']
    if holdout['modelSha256']!=manifest['sha256']:
        section=['','## Final structural holdout','','The archived holdout uses different model weights and does not evaluate this model.','']
    where=lines.index('## Dataset and training');lines[where:where]=section
    Path('docs/experiments.md').write_text('\n'.join(lines)+'\n')

if __name__=='__main__':main()
