import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createServer, type Server } from 'node:http';
import { spawn } from 'node:child_process';
import { mkdtemp, readFile, rm, access } from 'node:fs/promises';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tmpdir } from 'node:os';
import { chromium } from 'playwright';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
async function listen(server:Server){await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();assert.ok(address&&typeof address!=='string');return address.port;}
async function close(server:Server){await new Promise<void>(resolve=>server.close(()=>resolve()));}

test('local production UI captures Chromium, reviews real model evidence, exports, and reopens saved project', {timeout:120000}, async()=>{
 const workspace=await mkdtemp(join(tmpdir(),'renderguard-local-ui-'));
 const fixture=createServer((req,res)=>{res.writeHead(200,{'Content-Type':'text/html'});res.end(`<!doctype html><html lang="en"><meta charset="utf-8"><title>Settings fixture</title><style>html{background:#f2f6f0}body{font:18px system-ui;margin:0;padding:60px;color:#294036}main{border:1px solid #8fa38a;border-radius:12px;padding:40px;width:850px;background:white}h1{font-size:30px;margin:0 0 24px}p{margin:0 0 24px}button{position:relative;left:${req.url==='/after'?150:0}px;display:block;font:inherit;border:0;border-radius:7px;background:#355e40;color:white;padding:17px 28px;margin:15px 0}section{margin-top:30px;border:1px solid #c5d0bf;padding:20px}</style><main data-ready="true"><h1>Notification preferences</h1><p>Choose how you receive updates about your workspace.</p><section><h2>Product updates</h2><p>Monthly notes about features and improvements.</p><button id="action">Save preferences</button></section></main></html>`);});
 const targetPort=await listen(fixture);const reservation=createServer();const appPort=await listen(reservation);await close(reservation);
 const localPython=join(root,'.venv/bin/python');let python=process.env.PYTHON||localPython;try{await access(python);}catch{python='python3';}
 let logs='';const service=spawn(python,['-m','uvicorn','server.app:create_app','--factory','--host','127.0.0.1','--port',String(appPort)],{cwd:root,env:{...process.env,RENDERGUARD_WORKSPACE:workspace},stdio:['ignore','pipe','pipe']});service.stderr.on('data',chunk=>logs+=chunk);service.stdout.on('data',chunk=>logs+=chunk);
 let browser;
 try{
  const url=`http://127.0.0.1:${appPort}`;let started=false;for(let attempt=0;attempt<80;attempt++){try{const r=await fetch(`${url}/api/session`);if(r.ok){started=true;break;}}catch{}await new Promise(r=>setTimeout(r,250));}assert.ok(started,`Local application did not start: ${logs}`);
  browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1512,height:1040},acceptDownloads:true});const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});await page.goto(url);await page.locator('.mode-label').filter({hasText:'Local application'}).waitFor({timeout:10000}).catch(async()=>{throw new Error(`Local UI initialization failed: ${(await page.locator('body').innerText()).slice(0,3000)}; browser errors: ${errors.join(' | ')}`);});await page.getByRole('button',{name:'Compare screenshots',exact:true}).click();await page.getByRole('button',{name:'Capture local URLs',exact:true}).click();await page.getByLabel('Comparison name',{exact:true}).fill('Settings — intentional move');await page.getByLabel('Baseline development URL',{exact:true}).fill(`http://127.0.0.1:${targetPort}/before`);await page.getByLabel('Current development URL',{exact:true}).fill(`http://127.0.0.1:${targetPort}/after`);await page.getByLabel('Ready selector (optional)',{exact:true}).fill('[data-ready]');await page.getByText(/Declare measurable DOM contracts/).click();await page.getByLabel('Contract selector',{exact:true}).fill('#action');await page.getByRole('button',{name:'Add contract',exact:true}).click();await page.getByRole('button',{name:/Analyze comparison/}).click();await page.getByRole('heading',{name:'Changes',exact:true}).waitFor({timeout:60000});await page.locator('.environment-chip').filter({hasText:'Capture conditions verified'}).waitFor();await page.getByText('satisfied',{exact:true}).waitFor();assert.ok(await page.locator('.change-item').count()>0);assert.equal(await page.getByRole('heading',{name:'Settings — intentional move'}).count(),1);
  const snapshot=await page.evaluate(async()=>{const projects=await(await fetch('/api/projects')).json();const p=Array.isArray(projects)?projects[0]:projects.projects[0];const detail=await(await fetch(`/api/projects/${p.id}`)).json();return await(await fetch(`/api/runs/${detail.runs[0].id}`)).json();});assert.equal(snapshot.execution,'complete');assert.equal(snapshot.environment,'verified');assert.equal(snapshot.contracts[0].status,'satisfied');assert.ok(snapshot.predictions.length>0);
  await page.getByRole('button',{name:/Intentional change/}).last().click();await page.waitForFunction(()=>document.querySelector('.review-state.intentional_change')!==null);await page.getByText('Correct observation labels',{exact:false}).click();await page.getByLabel('Correct Layout displacement observation',{exact:true}).selectOption('yes');await page.waitForFunction(()=>document.querySelector('.workbench-footer')?.textContent?.includes('2 review events'));await page.getByRole('button',{name:'Use current as baseline'}).click();await page.getByRole('button',{name:'Project history',exact:true}).click();assert.equal(await page.locator('.baseline-row').count(),1);await page.locator('.history-list>button').first().click();
  await page.getByText('Export',{exact:true}).click();const event=page.waitForEvent('download');await page.getByRole('button',{name:'Versioned JSON evidence'}).click();const downloaded=await event;const output=join(workspace,'evidence.json');await downloaded.saveAs(output);const evidence=JSON.parse(await readFile(output,'utf8'));assert.equal(evidence.id,snapshot.id);assert.deepEqual(evidence.predictions,snapshot.predictions);assert.ok(evidence.images.before.startsWith('data:image/png;base64,'));assert.equal(evidence.decisions[evidence.analysis.candidates[0].id].observation.layout_displacement,true);
  await page.reload();await page.getByRole('heading',{name:'Settings — intentional move'}).waitFor();assert.ok(await page.locator('.review-state.intentional_change').count()>0);
  await page.getByRole('button',{name:'New comparison',exact:true}).click();await page.getByRole('button',{name:'Capture local URLs',exact:true}).click();await page.getByLabel('Comparison name',{exact:true}).fill('Unavailable development target');await page.getByLabel('Baseline development URL',{exact:true}).fill('http://127.0.0.1:9/');await page.getByLabel('Current development URL',{exact:true}).fill('http://127.0.0.1:9/');await page.getByRole('button',{name:/Analyze comparison/}).click();await page.getByRole('heading',{name:'Analysis error.',exact:true}).waitFor({timeout:30000});assert.equal(await page.getByRole('heading',{name:'Changes',exact:true}).count(),0);await page.reload();await page.getByRole('heading',{name:'Analysis error.',exact:true}).waitFor();assert.equal(await page.getByRole('heading',{name:'Changes',exact:true}).count(),0);assert.deepEqual(errors,[]);
  await context.close();
 }finally{await browser?.close();service.kill('SIGTERM');await new Promise<void>(resolve=>{if(service.exitCode!==null)resolve();else{service.once('exit',()=>resolve());setTimeout(()=>{service.kill('SIGKILL');resolve();},5000).unref();}});await close(fixture);await rm(workspace,{recursive:true,force:true});}
});
