import { gateFor, LABEL_NAMES, type Run } from './types';
const esc = (s: unknown) => String(s ?? '').replace(/[&<>"']/g,c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function download(data: string, type: string, name: string) { const url = URL.createObjectURL(new Blob([data], {type})); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url),1000); }
export function makeJSONReport(run: Run): string {
  return JSON.stringify({...run, gate: gateFor(run), reportSchema: 'renderguard-report/1'}, null, 2);
}
export function makeReport(run: Run): string {
  run = {...run, gate: gateFor(run)};
  if (run.gate.code === 3 && run.gate.reason !== 'A declared requirement could not be checked') {
    return `<!doctype html><html lang="en"><meta charset="utf-8"><title>RenderGuard report</title><h1>Gate 3: ${esc(run.gate.reason)}</h1><pre>${esc(makeJSONReport(run))}</pre></html>`;
  }
  const rows = run.analysis.candidates.map((c,i) => {const p=run.predictions.find(p=>p.candidateId===c.id); return `<tr><td>${i+1}</td><td>${c.box.x}, ${c.box.y} · ${c.box.width} × ${c.box.height}</td><td>${c.changedPixels.toLocaleString()}</td><td>${esc((run.decisions[c.id]?.decision || 'unreviewed').replaceAll('_',' '))}</td><td>${p ? Object.keys(LABEL_NAMES).map((label,k)=>`${esc(LABEL_NAMES[label])}: logit ${p.logits[k].toFixed(3)}${run.calibration?.classes[k]?.status==='calibrated' ? `, calibrated score ${p.scores[k].toFixed(3)}` : ' (uncalibrated)'}`).join('<br>') : 'No prediction'}</td><td>${esc(JSON.stringify(run.decisions[c.id]?.observation || {}))}</td></tr>`;}).join('');
  const encoded = JSON.stringify({...run, reportSchema:'renderguard-report/1'}).replaceAll('<','\\u003c');
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RenderGuard evidence snapshot</title><style>body{font:15px/1.6 system-ui,sans-serif;color:#203329;background:#f6f8f4;margin:40px auto;max-width:1280px;padding:0 24px}h1{font-size:38px;letter-spacing:-1.5px}h2{margin-top:36px}small{color:#647269}table{border-collapse:collapse;width:100%;font-size:12px;background:white}td,th{padding:12px;border:1px solid #d9e1d8;text-align:left;vertical-align:top}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px}img{max-width:100%;height:auto;border:1px solid #d9e1d8}.banner{padding:20px;background:#e4eddf;border-radius:12px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px} @media(max-width:700px){.pair{grid-template-columns:1fr}body{padding:12px;margin:12px auto}table{display:block;overflow:auto}}</style><header><small>RENDERGUARD / SAVED EVIDENCE</small><h1>${esc(run.name || 'Visual change review')}</h1><p>${esc(run.createdAt)} · Model ${esc(run.model.version)} · ${esc(run.environment)} environment</p></header><div class="banner"><b>Gate ${run.gate.code}: ${esc(run.gate.reason)}</b><br>Execution: ${esc(run.execution)}. This offline snapshot preserves evidence and saved decisions. It cannot update the source project or run a model. Visual observations are not defect probabilities.</div><h2>Original screenshots</h2><div class="pair"><div><h3>Baseline</h3><img alt="Original baseline screenshot" src="${esc(run.images?.before || run.beforeUrl)}"></div><div><h3>Current</h3><img alt="Original current screenshot" src="${esc(run.images?.after || run.afterUrl)}"></div></div><h2>Visual observations and review decisions</h2><p>${run.analysis.candidates.length} regions · ${run.analysis.changedPixels.toLocaleString()} changed pixels · height change ${run.analysis.heightDelta} px · ${esc(run.analysis.mode)} mode. Coordinates use original screenshot pixels. Difference regions locate change; they do not explain its cause.</p><table><thead><tr><th>Region</th><th>Original pixels</th><th>Changed pixels</th><th>Decision</th><th>Immutable model evidence</th><th>Corrected observations</th></tr></thead><tbody>${rows || '<tr><td colspan="6">No unmasked changes detected.</td></tr>'}</tbody></table><h2>Review priority</h2><pre>${esc(JSON.stringify(run.reviewPriority || {rule:"Original model evidence retained; no custom sort settings saved."},null,2))}</pre><h2>Declared contracts</h2><pre>${esc(JSON.stringify(run.contracts,null,2))}</pre><h2>Excluded masks</h2><pre>${esc(JSON.stringify(run.masks,null,2))}</pre><h2>Evidence identity</h2><pre>Run: ${esc(run.id)}\nModel SHA-256: ${esc(run.model.sha256)}\nPreprocessing: ${esc(run.analysis.version)}</pre><h2>Append-only review history</h2><pre>${esc(JSON.stringify(run.events,null,2))}</pre><script type="application/json" id="renderguard-evidence">${encoded}</script></html>`;
}
